server:
  port: 8061 #服务端口

grpc:
  port: 8062

spring:
  application:
    name: service-email #服务名称
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  datasource:
#    url: jdbc:mysql://192.168.152.128:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
#    username: root
#    password: mysql
#    driverClassName: com.mysql.jdbc.Driver
#  redis:
#    database: 5
#    host: 192.168.152.128
#    port: 6379
#    password:
  messages:
    basename: message/messages,message/validation/messages,message/business/messages  #国际化配置
    encoding: UTF-8
  mail:
    host: smtp.qq.com
    username: 2637977081@qq.com
    password: fzugpomwwjqxebbf
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
  boot:
    admin:
      client:
        url: http://service-monitor:8091
        instance:
          prefer-ip: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.univer.*.po