// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.univer.base.grpc.message;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jsonData = 1;</code>
   */
  java.lang.String getJsonData();
  /**
   * <code>string jsonData = 1;</code>
   */
  com.google.protobuf.ByteString
      getJsonDataBytes();
}
