server:
  port: 8051 #服务端口

spring:
  application:
    name: service-credit #成绩管理
  datasource:
    url: jdbc:mysql://localhost:3306/credit?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 300000
      maximum-pool-size: 50
      minimum-idle: 10
  messages:
    basename: message/base/messages,message/validation/messages,message/business/messages  #国际化配置
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    auto: true
    proxy-target-class: true
  resources:
    add-mappings: false
  redis:
    database: 10
    host: localhost
    port: 6379
  servlet:
    multipart:
      maxFileSize: 1024Mb
      maxRequestSize: 1024Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        url: http://localhost:8091
        instance:
          prefer-ip: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.univer.*.po

mapper:
  mappers: com.univer.base.mapper.BaseMapper
  not-empty: false
  identity: MYSQL

#日志控制
logging:
  root: /opt/service/log
  config: classpath:service-logback.xml
  file: /opt/service/log/${spring.application.name}/${spring.application.name}.info.log