// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.univer.base.grpc.account;

public final class Account {
  private Account() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_AccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_AccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_AccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_AccountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\007account\"\036\n\016AccountRequest\022" +
      "\014\n\004json\030\001 \001(\t\"\037\n\017AccountResponse\022\014\n\004json" +
      "\030\001 \001(\t2\343\002\n\016AccountService\022=\n\006detail\022\027.ac" +
      "count.AccountRequest\032\030.account.AccountRe" +
      "sponse\"\000\022@\n\tlistByIds\022\027.account.AccountR" +
      "equest\032\030.account.AccountResponse\"\000\022C\n\016fi" +
      "ndDictByType\022\027.account.AccountRequest\032\030." +
      "account.AccountResponse\022B\n\rfindMapByType" +
      "\022\027.account.AccountRequest\032\030.account.Acco" +
      "untResponse\022G\n\020findNameByUserId\022\027.accoun" +
      "t.AccountRequest\032\030.account.AccountRespon" +
      "se\"\000B)\n\034com.univer.base.grpc.accountB\007Ac" +
      "countP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_account_AccountRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_account_AccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_AccountRequest_descriptor,
        new java.lang.String[] { "Json", });
    internal_static_account_AccountResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_account_AccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_AccountResponse_descriptor,
        new java.lang.String[] { "Json", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
