// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.univer.base.grpc.account;

public interface AccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.AccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string json = 1;</code>
   */
  java.lang.String getJson();
  /**
   * <code>string json = 1;</code>
   */
  com.google.protobuf.ByteString
      getJsonBytes();
}
