server:
  port: 8061 #服务端口

spring:
  application:
    name: service-course #成绩管理
  messages:
    basename: message/base/messages,message/validation/messages,message/business/messages  #国际化配置
    encoding: UTF-8
  boot:
    admin:
      client:
        url: http://service-monitor:8091
        instance:
          prefer-ip: true
  datasource:
    url: jdbc:mysql://localhost:3306/credit?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 300000
      maximum-pool-size: 50
      minimum-idle: 10


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.univer.*.po

mapper:
  mappers: com.univer.base.mapper.BaseMapper
  not-empty: false
  identity: MYSQL