server:
  port: 8031 #服务端口

grpc:
  port: 8032

spring:
  application:
    name: service-account #服务名称
  datasource:
    url: jdbc:mysql://192.168.152.128:3306/account?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: lvgang
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 300000
      maximum-pool-size: 50
      minimum-idle: 10
  messages:
    basename: message/base/messages,message/validation/messages,message/business/messages  #国际化配置
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    auto: true
    proxy-target-class: true
  resources:
    add-mappings: false
  redis:
    database: 10
    host: 192.168.152.128
    port: 6379
  servlet:
    multipart:
      maxFileSize: 1024Mb
      maxRequestSize: 1024Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        url: http://service-monitor:8091
        instance:
          prefer-ip: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.univer.*.po

mapper:
  mappers: com.univer.base.mapper.BaseMapper
  not-empty: false
  identity: MYSQL

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jjwt:
  secret: bei0hua1university2graduation3design  #JWT私钥
  ttlMillis: 86400000  #token有效时间（毫秒）

bcrypt:
  salt: 4 #加密盐的长度

captcha:
  timeout: 300000 #验证码有效期

#服务停止
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true

#日志控制
logging:
  root: /opt/service/log
  config: classpath:service-logback.xml
  file: /opt/service/log/${spring.application.name}/${spring.application.name}.info.log