server:
  port: 8061 #服务端口

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: service-course #成绩管理
  messages:
    basename: message/base/messages,message/validation/messages,message/business/messages  #国际化配置
    encoding: UTF-8
  boot:
    admin:
      client:
        url: http://service-monitor:8091
        instance:
          prefer-ip: true