server:
  port: 9031 #服务端口

grpc:
  port: 9032

spring:
  application:
    name: service-account #服务名称
  datasource:
    url: jdbc:mysql://univer-mysql.home.univer:3306/account_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: univer
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 300000
      maximum-pool-size: 50
      minimum-idle: 10
  messages:
    basename: message/base/messages,message/validation/messages,message/business/messages  #国际化配置
    encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    auto: true
    proxy-target-class: true
  resources:
    add-mappings: false
  redis:
    database: 10
    host: univer-redis.home.univer
    port: 6379
  servlet:
    multipart:
      maxFileSize: 1024Mb
      maxRequestSize: 1024Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.univer.*.po

mapper:
  mappers: com.univer.base.mapper.BaseMapper
  not-empty: false
  identity: MYSQL

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jjwt:
  secret: sh8e2a6d7d3d33a7b6b98b0op7bce6ef45c076d1d4116f1997bf2029c3ac2328  #JWT私钥
  ttlMillis: 86400000  #token有效时间（毫秒）

bcrypt:
  salt: 4 #加密盐的长度

captcha:
  timeout: 300000 #验证码有效期

#服务停止
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true

#日志控制
logging:
  path: /opt/service/log
  config: classpath:service-logback.xml