// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.univer.base.grpc.model;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ModelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_ModelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ModelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_ModelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\005model\" \n\014ModelRequest\022\020\n\010" +
      "jsonData\030\001 \001(\t\"!\n\rModelResponse\022\020\n\010jsonD" +
      "ata\030\001 \001(\t2F\n\014ModelService\0226\n\007predict\022\023.m" +
      "odel.ModelRequest\032\024.model.ModelResponse\"" +
      "\000B%\n\032com.univer.base.grpc.modelB\005ModelP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_ModelRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_ModelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_ModelRequest_descriptor,
        new java.lang.String[] { "JsonData", });
    internal_static_model_ModelResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_ModelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_ModelResponse_descriptor,
        new java.lang.String[] { "JsonData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
