// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.univer.base.grpc.model;

public interface ModelResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.ModelResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jsonData = 1;</code>
   */
  java.lang.String getJsonData();
  /**
   * <code>string jsonData = 1;</code>
   */
  com.google.protobuf.ByteString
      getJsonDataBytes();
}
