// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package com.univer.base.grpc.storage;

public final class Storage {
  private Storage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_storage_StorageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_storage_StorageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_storage_StorageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_storage_StorageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstorage.proto\022\007storage\"\"\n\016StorageReque" +
      "st\022\020\n\010jsonData\030\001 \001(\t\"#\n\017StorageResponse\022" +
      "\020\n\010jsonData\030\001 \001(\t2\233\001\n\016StorageService\022F\n\r" +
      "objectStorage\022\027.storage.StorageRequest\032\030" +
      ".storage.StorageResponse\"\000(\001\022A\n\nlogStora" +
      "ge\022\027.storage.StorageRequest\032\030.storage.St" +
      "orageResponse\"\000B)\n\034com.univer.base.grpc." +
      "storageB\007StorageP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_storage_StorageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_storage_StorageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_storage_StorageRequest_descriptor,
        new java.lang.String[] { "JsonData", });
    internal_static_storage_StorageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_storage_StorageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_storage_StorageResponse_descriptor,
        new java.lang.String[] { "JsonData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
