// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

package com.univer.base.grpc.storage;

public interface StorageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:storage.StorageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jsonData = 1;</code>
   */
  java.lang.String getJsonData();
  /**
   * <code>string jsonData = 1;</code>
   */
  com.google.protobuf.ByteString
      getJsonDataBytes();
}
